
name: Compilar APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Instalar Gradle específico
        run: |
          wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
          sudo unzip -d /opt/gradle gradle-8.0-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.0/bin
          gradle -v

      - name: Compilar con Gradle 8.0
        run: /opt/gradle/gradle-8.0/bin/gradle assembleDebug

      - name: Subir el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: App-Descargada
          path: app/build/outputs/apk/debug/*.apk
